/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import ClassEntity.Account;
import ClassEntity.NhanSu;
import DataAccess.Account_DTA;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;


public class QuanLyTK extends javax.swing.JPanel {

    public ArrayList<Account> list = new ArrayList<Account>();
    Account_DTA accountdta = new Account_DTA();

    /**
     * Creates new form QuanLyTK
     */
    public QuanLyTK() {
        initComponents();
        showTable();
        selectionTable();
    }

    // Hàm click vào tên sinh viên trong bảng
    void selectionTable() {
// Tạo danh sách lựa chọn của người dùng tên bảng và thiết lập chỉ chọn 1.
        ListSelectionModel listselectionmodel = table.getSelectionModel();
        listselectionmodel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
// Thêm hàm lắng nghe sự kiện lựa chọn trên bảng
        listselectionmodel.addListSelectionListener(new ListSelectionListener() {
// Thêm hàm thay đổi giá trị lựa chọn
            @Override
            public void valueChanged(ListSelectionEvent e) {
// Lấy danh sách các cột và các hàng lựa chọn
                int[] rows = table.getSelectedRows();
                int[] colums = table.getSelectedColumns();
// Nếu có hàng được lựa chọn thì chạy tiếp
                if (colums.length > 0 && rows.length > 0) {
// Gán các giá trị từ bảng vào các ô TexField bên dưới
                    txtuser.setText(String.valueOf(table.getValueAt(rows[0], 0)));
                    txtuser.setEditable(false);
                    txtpassw.setText(String.valueOf(table.getValueAt(rows[0], 1)));
                    txtper.setText(String.valueOf(table.getValueAt(rows[0], 2)));
                }
            }
        });
    }

// Hàm hiển thị bảng
    void showTable() {
// Lấy danh sách sinh viên tưf file QuanLySV.dat
        if (accountdta.docFile() != null) {
            list = accountdta.docFile();
        }
        DefaultTableModel dtm = new DefaultTableModel();
        table.setModel(dtm);
// Thêm tiêu đề cho bảng
        dtm.addColumn("Tên NV");
        dtm.addColumn("Mật khẩu");
        dtm.addColumn("Quyền");

// Nếu danh sách khác null thì thực hiện tiếp
        if (list != null) {
            for (int i = 0; i < list.size(); i++) {
                Account a = list.get(i);
                dtm.addRow(new Object[]{a.getUsername(), a.getPassword(), a.getPermission()});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btthem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btsua = new javax.swing.JButton();
        btxoa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtpassw = new javax.swing.JTextField();
        txtper = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jtf_timkiem = new javax.swing.JTextField();
        btn_Timkiem = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(821, 597));

        btthem.setBackground(new java.awt.Color(0, 204, 204));
        btthem.setText("Thêm");
        btthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("QUẢN LÝ TÀI KHOẢN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(313, 313, 313))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
        );

        btsua.setBackground(new java.awt.Color(0, 204, 204));
        btsua.setText("Sửa");
        btsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsuaActionPerformed(evt);
            }
        });

        btxoa.setBackground(new java.awt.Color(0, 204, 204));
        btxoa.setText("Xóa");
        btxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxoaActionPerformed(evt);
            }
        });

        jLabel2.setText("UserName:");

        jLabel3.setText("PassWord:");

        jLabel4.setText("Permission:");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setText("Hủy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_Timkiem.setBackground(new java.awt.Color(0, 204, 204));
        btn_Timkiem.setText("Tìm kiếm");
        btn_Timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 286, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtuser)
                            .addComponent(txtpassw)
                            .addComponent(txtper, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(286, 286, 286))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btthem)
                        .addGap(18, 18, 18)
                        .addComponent(btsua, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jtf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Timkiem)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtpassw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btthem)
                    .addComponent(btsua)
                    .addComponent(btxoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Timkiem)
                    .addComponent(jButton1))
                .addGap(150, 150, 150))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemActionPerformed
        // TODO add your handling code here:
        if (accountdta.docFile() != null) {
            list = accountdta.docFile();
        }
        String name = txtuser.getText();
        String pass = txtpassw.getText();
        String per = txtper.getText();
        if (name.equals("") || pass.equals("") || per.equals("")) {
            JOptionPane.showMessageDialog(this, "Các trường không được bỏ trống");
        } else {
            if (Account.check(name) == 1) {
                JOptionPane.showMessageDialog(this,"Ten tai khoan da ton tai!");
            } else {
                Account a = new Account(name, pass, per);
                list.add(a);
                accountdta.ghiFile(list);
                txtuser.setText("");
                txtpassw.setText("");
                txtper.setText("");
                showTable();
                JOptionPane.showMessageDialog(this, "Thêm thành công");
            }
        }
    }//GEN-LAST:event_btthemActionPerformed

    private void btsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsuaActionPerformed
        // TODO add your handling code here:
        String name = txtuser.getText();
        if (name.equals("")) {
            JOptionPane.showConfirmDialog(this, "click vào tài khoản muốn cập nhật");
        } else {
            if (accountdta.docFile() != null) {
                list = accountdta.docFile();
            }
            for (Account a : list) {
                if (a.getUsername().equals(name)) {
                    a.setPassword(txtpassw.getText());
                    a.setPermission(txtper.getText());
                }
            }
            accountdta.ghiFile(list);
            showTable();
            txtuser.setText("");
            txtpassw.setText("");
            txtper.setText("");
            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
        }

    }//GEN-LAST:event_btsuaActionPerformed

    private void btxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxoaActionPerformed
        // TODO add your handling code here:
        ArrayList<Account> list1 = new ArrayList<Account>();
        String name = txtuser.getText();
        if (name.equals("")) {
            JOptionPane.showConfirmDialog(this, "click vào tài khoản muốn xóa");
        } else {
            int result = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa trường này?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                if (accountdta.docFile() != null) {
                    list = accountdta.docFile();
                }
                for (Account a : list) {
                    if (!a.getUsername().equals(name)) {
                        list1.add(a);
                    }
                }
                accountdta.ghiFile(list1);
                showTable();
                txtuser.setText("");
                txtpassw.setText("");
                txtper.setText("");
                JOptionPane.showMessageDialog(this, "Xóa thành công");
            }

        }
    }//GEN-LAST:event_btxoaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtuser.setText("");
        txtuser.setEditable(true);
        txtpassw.setText("");
        txtper.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_TimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimkiemActionPerformed
        // TODO add your handling code here:
         int count=0;
        for (int i = 0; i < table.getRowCount(); i++) {
            if (String.valueOf(table.getValueAt(i, 0)).equals(jtf_timkiem.getText())) {
                count++;
                DefaultTableModel dtm = new DefaultTableModel();
                table.setModel(dtm);
                // Thêm tiêu đề cho bảng
                dtm.addColumn("Tên NV");
                dtm.addColumn("Mật khẩu");
                dtm.addColumn("Quyền");
                //insert into table
                Account a = list.get(i);
                dtm.addRow(new Object[]{a.getUsername(), a.getPassword(), a.getPermission()});
            }
        }
        if(count == 0){
            JOptionPane.showMessageDialog(this, "Không tìm thấy kết quả", "Warning", JOptionPane.WARNING_MESSAGE);
            showTable();
        }
    }//GEN-LAST:event_btn_TimkiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Timkiem;
    private javax.swing.JButton btsua;
    private javax.swing.JButton btthem;
    private javax.swing.JButton btxoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtf_timkiem;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtpassw;
    private javax.swing.JTextField txtper;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
