/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import ClassEntity.NhanSu;
import ClassEntity.TuyenDung;
import DataAccess.TuyenDung_DTA;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;


public class QuanLyTuyenDung extends javax.swing.JPanel { // Tạo lớp QLTD kế thừa từ giao diện
    public ArrayList<TuyenDung> list = new ArrayList<TuyenDung>(); // tạo mảng ds TuyenDung ArrayList
    TuyenDung_DTA tuyendungdta = new TuyenDung_DTA(); // Tạo 1 lớp đối tượng cho lớp ở file TuyenDung_DTA

    /**
     * Creates new form QuanLyTuyenDung
     */
    public QuanLyTuyenDung() { // hiển thị thông tin tuyển dụng 
        initComponents();
        showTable(); 
        selectionTable(); 
    }

    // Hàm click vào tên sinh viên trong bảng
    void selectionTable() {
// Tạo danh sách lựa chọn của người dùng tên bảng và thiết lập chỉ chọn 1.
        ListSelectionModel listselectionmodel = table.getSelectionModel();
        listselectionmodel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
// Thêm hàm lắng nghe sự kiện lựa chọn trên bảng
        listselectionmodel.addListSelectionListener(new ListSelectionListener() {
// Thêm hàm thay đổi giá trị lựa chọn
            @Override
            public void valueChanged(ListSelectionEvent e) {
// Lấy danh sách các cột và các hàng lựa chọn
                int[] rows = table.getSelectedRows();
                int[] colums = table.getSelectedColumns();
// Nếu có hàng được lựa chọn thì chạy tiếp
                if (colums.length > 0 && rows.length > 0) {
// Gán các giá trị từ bảng vào các ô TexField bên dưới
                    txtmaut.setText(String.valueOf(table.getValueAt(rows[0], 0)));
                    txtmaut.setEditable(false);
                    txttenut.setText(String.valueOf(table.getValueAt(rows[0], 1)));
                    txtgt.setText(String.valueOf(table.getValueAt(rows[0], 2)));
                    txtngsinh.setText(String.valueOf(table.getValueAt(rows[0], 3)));
                    txtsdt.setText(String.valueOf(table.getValueAt(rows[0], 4)));
                    txtemail.setText(String.valueOf(table.getValueAt(rows[0], 5)));
                    txtdiachi.setText(String.valueOf(table.getValueAt(rows[0], 6)));
                    txttrinhdo.setText(String.valueOf(table.getValueAt(rows[0], 7)));
                    txtchuyennganh.setText(String.valueOf(table.getValueAt(rows[0], 8)));
                    txtxeploai.setText(String.valueOf(table.getValueAt(rows[0], 9)));
                    txtvitri.setText(String.valueOf(table.getValueAt(rows[0], 10)));
                }
            }
        });
    }

// Hàm hiển thị bảng
    void showTable() {
// Lấy danh sách nguoi tuyen dung tưf file TuyenDung.dat
        if (tuyendungdta.docFile() != null) {
            list = tuyendungdta.docFile();
        }
        //Đặt bảng về mặc định không cột không hàng
        DefaultTableModel dtm = new DefaultTableModel();
        table.setModel(dtm);
// Thêm tiêu đề cho bảng
        dtm.addColumn("Mã");
        dtm.addColumn("Tên");
        dtm.addColumn("Giới tính");
        dtm.addColumn("Ngày sinh");
        dtm.addColumn("Số điện thoại");
        dtm.addColumn("Email");
        dtm.addColumn("Địa chỉ");
        dtm.addColumn("Trình độ");
        dtm.addColumn("Chuyên ngành");
        dtm.addColumn("Xếp loại");
        dtm.addColumn("Vị trí ứng tuyển");
// Nếu danh sách khác null thì thực hiện tiếp
        if (list != null) {
            for (int i = 0; i < list.size(); i++) {
                TuyenDung a = list.get(i);
                dtm.addRow(new Object[]{a.getMa(), a.getTen(), a.getGtinh(), a.getNgsinh(), a.getSdt(), a.getEmail(), a.getDchi(),
                    a.getTrinhdo(), a.getCnganh(), a.getXeploai(), a.getVtungtuyen()});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btxoa = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtmaut = new javax.swing.JTextField();
        txttenut = new javax.swing.JTextField();
        txtgt = new javax.swing.JTextField();
        txtngsinh = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        txttrinhdo = new javax.swing.JTextField();
        txtchuyennganh = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtxeploai = new javax.swing.JTextField();
        txtvitri = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btthem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btsua = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jtf_timkiem = new javax.swing.JTextField();
        btnTimkiem = new javax.swing.JButton();

        btxoa.setBackground(new java.awt.Color(0, 204, 204));
        btxoa.setText("Xóa");
        btxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxoaActionPerformed(evt);
            }
        });

        jLabel8.setText("Địa chỉ:");

        jLabel9.setText("Trình độ:");

        jLabel11.setText("Chuyên ngành:");

        jLabel12.setText("Xếp loại:");

        jLabel13.setText("Vị trí:");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("THÔNG TIN TUYỂN DỤNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(289, 289, 289))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel2.setText("Mã ứng tuyển:");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel3.setText("Tên ứng tuyển:");

        jLabel4.setText("Giới tính:");

        btthem.setBackground(new java.awt.Color(0, 204, 204));
        btthem.setText("Thêm");
        btthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemActionPerformed(evt);
            }
        });

        jLabel5.setText("Ngày sinh:");

        btsua.setBackground(new java.awt.Color(0, 204, 204));
        btsua.setText("Sửa");
        btsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsuaActionPerformed(evt);
            }
        });

        jLabel6.setText("SDT:");

        jLabel7.setText("Email:");

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setText("Hủy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnTimkiem.setBackground(new java.awt.Color(0, 204, 204));
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtmaut))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttenut, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(txtgt)
                            .addComponent(txtngsinh))))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsdt)
                    .addComponent(txtemail)
                    .addComponent(txtdiachi)
                    .addComponent(txttrinhdo, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtchuyennganh)
                    .addComponent(txtxeploai)
                    .addComponent(txtvitri))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btthem, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btsua, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimkiem)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(txtmaut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txttenut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtgt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtngsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txttrinhdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtchuyennganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtxeploai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txtvitri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btthem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btsua)
                        .addComponent(btxoa)
                        .addComponent(jtf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTimkiem)
                        .addComponent(jButton1)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemActionPerformed
        
       // Nếu ds TuyenDung rỗng thì khởi tạo mảng list = tuyendungdata.docFile();
        if (tuyendungdta.docFile() != null) {
            list = tuyendungdta.docFile();
        }
        //khai báo biến để gán giá trị bằng phương thức getText
        String ma = txtmaut.getText();
        String name = txttenut.getText();
        String gioitinh = txtgt.getText();
        String ngaysinh = txtngsinh.getText();
        String sdt = txtsdt.getText();
        String email = txtemail.getText();
        String diachi = txtdiachi.getText();
        String trinhdo = txttrinhdo.getText();
        String chuyennganh = txtchuyennganh.getText();
        String xeploai = txtxeploai.getText();
        String vitri = txtvitri.getText(); 
        // bắt lỗi khi nhập thiếu thông tin
        if (ma.equals("") || name.equals("") || gioitinh.equals("") || ngaysinh.equals("") || sdt.equals("") || email.equals("") 
                || diachi.equals("") || trinhdo.equals("") || chuyennganh.equals("") || xeploai.equals("") || vitri.equals("")) {
            JOptionPane.showMessageDialog(this, "Các trường không được bỏ trống");
        } else { 
            // kiểm tra mã nếu trùng ko cho thêm
            if (TuyenDung.check(ma) == 1) { 
                JOptionPane.showMessageDialog(this, "Ma tuyen dung da ton tai!");
            } else { // Ngược lại khi nhập đầy đủ các trường 
                TuyenDung a = new TuyenDung(ma, name, gioitinh, ngaysinh, sdt, email, diachi, trinhdo, chuyennganh, xeploai, vitri);
                // thì sẽ tạo ra 1 TuyenDung mới được ghi lại vào file và hiện lên màn hình
                list.add(a);
                tuyendungdta.ghiFile(list);  // ghi file vào ds
                txtmaut.setText("");
                txttenut.setText("");
                txtgt.setText("");
                txtngsinh.setText("");
                txtsdt.setText("");
                txtemail.setText("");
                txtdiachi.setText("");
                txttrinhdo.setText("");
                txtchuyennganh.setText("");
                txtxeploai.setText("");
                txtvitri.setText("");
                showTable();
                JOptionPane.showMessageDialog(this, "Thêm thành công"); // báo thêm thành công
            }
        }
    }//GEN-LAST:event_btthemActionPerformed

    private void btsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsuaActionPerformed
        // TODO add your handling code here:
        String ma = txtmaut.getText();
        if (ma.equals("")) { // nếu trường mã để trống tức là chưa chọn dk TuyenDung để sửa ht thông báo click vào ... 
            JOptionPane.showMessageDialog(this, "click vào trường muốn cập nhật");
        } else {
            if (tuyendungdta.docFile() != null) {
                list = tuyendungdta.docFile();
            }
            for (TuyenDung a : list) {
                if (a.getMa().equals(ma)) { // sau khi click vào TuyenDung muốn sửa 
                    a.setTen(txttenut.getText()); // sửa tên
                    a.setGtinh(txtgt.getText()); // sửa giới tính
                    a.setNgsinh(txtngsinh.getText()); // sửa ngày sinh
                    a.setSdt(txtsdt.getText()); // sửa sdt
                    a.setEmail(txtemail.getText()); // sửa email
                    a.setDchi(txtdiachi.getText()); // sửa địa chỉ
                    a.setTrinhdo(txttrinhdo.getText()); // sửa trình độ
                    a.setCnganh(txtchuyennganh.getText()); // sửa chuyên ngành
                    a.setXeploai(txtxeploai.getText()); // sửa xếp loại
                    a.setVtungtuyen(txtvitri.getText()); // sửa vị trí ứng tuyển
                }
            }
            tuyendungdta.ghiFile(list); // lưu lại trong danh sách
            showTable();
            txtmaut.setText("");
            txttenut.setText("");
            txtgt.setText("");
            txtngsinh.setText("");
            txtsdt.setText("");
            txtemail.setText("");
            txtdiachi.setText("");
            txtchuyennganh.setText("");
            txttrinhdo.setText("");
            txtxeploai.setText("");
            txtvitri.setText("");
            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
        }
    }//GEN-LAST:event_btsuaActionPerformed

    private void btxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxoaActionPerformed
        // TODO add your handling code here: // THop người quản trị muốn hủy ko sửa xóa  thì các giá trị ô input =null
        ArrayList<TuyenDung> list1 = new ArrayList<TuyenDung>();
        String ma = txtmaut.getText();
        if (ma.equals("")) {
            JOptionPane.showMessageDialog(this, "click vào trường muốn xóa");
        } else {
            int result = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa trường này?", "Confirm", JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                if (tuyendungdta.docFile() != null) {
                    list = tuyendungdta.docFile();
                }
                for (TuyenDung a : list) {
                    if (!a.getMa().equals(ma)) {
                        list1.add(a);
                    }
                }
                tuyendungdta.ghiFile(list1);
                showTable();
                txtmaut.setText("");
                txttenut.setText("");
                txtgt.setText("");
                txtngsinh.setText("");
                txtsdt.setText("");
                txtemail.setText("");
                txtdiachi.setText("");
                txtchuyennganh.setText("");
                txttrinhdo.setText("");
                txtxeploai.setText("");
                txtvitri.setText("");
                JOptionPane.showMessageDialog(this, "Xóa thành công");
            }

        }
    }//GEN-LAST:event_btxoaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtmaut.setText("");
        txtmaut.setEditable(true);
        txttenut.setText("");
        txtgt.setText("");
        txtngsinh.setText("");
        txtsdt.setText("");
        txtemail.setText("");
        txtdiachi.setText("");
        txtchuyennganh.setText("");
        txttrinhdo.setText("");
        txtxeploai.setText("");
        txtvitri.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        // TODO add your handling code here:
         int count = 0;
        for (int i = 0; i < table.getRowCount(); i++) {
            if (String.valueOf(table.getValueAt(i, 0)).equals(jtf_timkiem.getText()) || 
                    String.valueOf(table.getValueAt(i, 1)).equals(jtf_timkiem.getText())) {
                count++;
                DefaultTableModel dtm = new DefaultTableModel();
                table.setModel(dtm);
                // Thêm tiêu đề cho bảng
                dtm.addColumn("Mã");
                dtm.addColumn("Tên");
                dtm.addColumn("Giới tính");
                dtm.addColumn("Ngày sinh");
                dtm.addColumn("Số điện thoại");
                dtm.addColumn("Email");
                dtm.addColumn("Địa chỉ");
                dtm.addColumn("Trình độ");
                dtm.addColumn("Chuyên ngành");
                dtm.addColumn("Xếp loại");
                dtm.addColumn("Vị trí ứng tuyển");

                //insert into table
                TuyenDung a = list.get(i);
                dtm.addRow(new Object[]{a.getMa(), a.getTen(), a.getGtinh(), a.getNgsinh(), a.getSdt(), a.getEmail(), 
                    a.getDchi(), a.getTrinhdo(), a.getCnganh(), a.getXeploai(), a.getVtungtuyen()});
            }
        }
        if(count == 0){
            JOptionPane.showMessageDialog(this, "Không tìm thấy kết quả", "Warning", JOptionPane.WARNING_MESSAGE);
            showTable();
        }
    }//GEN-LAST:event_btnTimkiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btsua;
    private javax.swing.JButton btthem;
    private javax.swing.JButton btxoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtf_timkiem;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtchuyennganh;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtgt;
    private javax.swing.JTextField txtmaut;
    private javax.swing.JTextField txtngsinh;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txttenut;
    private javax.swing.JTextField txttrinhdo;
    private javax.swing.JTextField txtvitri;
    private javax.swing.JTextField txtxeploai;
    // End of variables declaration//GEN-END:variables
}
